// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mqpevmlaeoesuyrboakn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xcGV2bWxhZW9lc3V5cmJvYWtuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNDk2MzMsImV4cCI6MjA3MzkyNTYzM30.QkFEZkW4_m72-C_xaBNp3lQlNvDUVjhjST0aN0qLgsI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});